name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  test:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    strategy:
      matrix:
        repo:
          - vulkan
          - wayland
          - X11
          - glfw
          - cimgui
          - spirv
          - glslang
          - shaderc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo }}.zig"

    - uses: tiawl/spaceporn-dep-action-bot@ci
      with:
        token: "${{ github.token }}"
